{% set name = "python-frontmatter" %}
{% set version = "1.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/python-frontmatter-{{ version }}.tar.gz
  sha256: 7118d2bd56af9149625745c58c9b51fb67e8d1294a0c76796dafdc72c36e5f6d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - pyyaml

test:
  imports:
    - frontmatter
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/eyeseast/python-frontmatter
  summary: Parse and manage posts with YAML (or other) frontmatter
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - abkfenris
