{% set name = "python-frontmatter" %}
{% set version = "1.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/python-frontmatter-{{ version }}.tar.gz
  sha256: a6a082844fc601f34e4dd576bed8fcb5ef19112166e087629e4d6ba9bf4f7c35

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - pyyaml

test:
  imports:
    - frontmatter
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/eyeseast/python-frontmatter
  summary: Parse and manage posts with YAML (or other) frontmatter
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - abkfenris
